apiVersion: apps/v1
kind: DaemonSet   
metadata:
  name: xdclass-ds
  namespace: dev
spec:
  selector: 
    matchLabels:
      app: xdclass-nginx-pod
  template:
    metadata:
      labels:
        app: xdclass-nginx-pod
    spec:
      containers:
      - name: xdclass-nginx
        image: nginx:1.23.0
        imagePullPolicy: IfNotPresent
