apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: k8s-springboot-redis
  name: k8s-springboot-redis
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-springboot-redis
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: k8s-springboot-redis
    spec:
      imagePullSecrets:
      - name: k8s-spring-redis-secret
      containers:
      - image: registry.cn-shenzhen.aliyuncs.com/k8s-springboot-redis-dev/k8s-springboot-redis-dev:1.0
        name: k8s-springboot-redis
        imagePullPolicy: Always
        resources: {}
status: {}
