apiVersion: v1
kind: PersistentVolume
metadata:
  name:  xdclass-pv1
spec:
  capacity: 
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.251
    path: /opt/nfsdata/pv1
    

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name:  xdclass-pv2
spec:
  capacity: 
    storage: 2Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.251
    path: /opt/nfsdata/pv2
