apiVersion: v1
kind: Pod
metadata:
  name: xdclass-pod1
  namespace: dev
spec:
  containers:
  - name: xdclass-busybox
    image: busybox
    command: ["/bin/sh","-c","while true;do echo hello xdclass pod1 >> /opt/print.txt; sleep 5; done;"]
    volumeMounts:
    - name: volume
      mountPath: /opt/
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: xdclass-pvc1
        readOnly: false
---
apiVersion: v1
kind: Pod
metadata:
  name: xdclass-pod2
  namespace: dev
spec:
  containers:
  - name: xdclass-busybox
    image: busybox
    command: ["/bin/sh","-c","while true;do echo hello xdclass pod2 >> /opt/print.txt; sleep 5; done;"]
    volumeMounts:
    - name: volume
      mountPath: /opt/
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: xdclass-pvc2
        readOnly: false
